name: Snuggle Party
favicon: null
layout_spectrum: 0.7780743637122214
typography_spectrum: 0.7304579757619649
title: 'Building Community with Nourishing Platonic Touch, Snuggle, & Cuddle Events'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffdd0c'
    - '#fe0002'
    - '#8f7846'
    - '#000000'
    - '#fefefe'
  brandStrength: 0.7935893128160387
  lightness: 0.27459708834066987
  saturation: 0.6875
  rhythmicContrast: 0.19399415259249508
purpose: []
